import config from "../../config.js";

export default {
  ERROR_NO_DEFINED_CODE: "5000",
  ERROR_NO_DEFINED_MESSAGE: "ERROR NO CONTROLADO",

  //#region auth errors
  ERROR_USER_NO_AUTHORIZED_CODE: "5001",
  ERROR_USER_NO_AUTHORIZED_MESSAGE: "NO AUTORIZADO",

  ERROR_TOKEN_EXPIRED_CODE: "5002",
  ERROR_TOKEN_EXPIRED_MESSAGE: "TOKEN EXPIRADO",

  ERROR_SING_IN_CODE: "5005",
  ERROR_SING_IN_MESSAGE: "NO SE PUDO INICIAR SESION",

  ERROR_SING_UP_CODE: "5006",
  ERROR_SING_UP_MESSAGE: "NO SE PUDO REGISTRAR",

  ERROR_PARAM_EXIST_CODE: "5007",
  ERROR_PARAM_EXIST_MESSAGE: "El {0} {1} ya existe.",

  ERROR_PARAM_USE_CODE: "5008",
  ERROR_PARAM_USE_MESSAGE: "Ya estas usando {0} como {1}.",

  ERROR_PASSWORD_FAIL_CODE: "5010",
  ERROR_PASSWORD_FAIL_MESSAGE: "CONTRASEÑA INCORRECTA",
  
  ERROR_PASSWORD_LENGTH_CODE: "5011",
  ERROR_PASSWORD_LENGTH_MESSAGE: "La password debe contener " + config.PASSWORD_LENGHT + " digitos como minimo",
  
  ERROR_USERNAME_LENGTH_CODE: "5014",
  ERROR_USERNAME_LENGTH_MESSAGE: "El username debe contener " + config.USERNAME_LENGHT + " digitos como minimo",
  
  ERROR_CODE_VALID_CODE: "5017",
  ERROR_CODE_VALID_MESSAGE: "El {0} no es valido",
  //#endregion

  //#region request errors
  ERROR_DATA_HEADER_REQUIRED_CODE: "5022",
  ERROR_DATA_HEADER_REQUIRED_MESSAGE: "PARAMETRO {0} EN CABECERA ES REQUERIDO O NO ES VALIDO",

  ERROR_DATA_BODY_REQUIRED_CODE: "5021",
  ERROR_DATA_BODY_REQUIRED_MESSAGE: "EL CAMPO {0} ES REQUERIDO O NO ES VALIDO.",
  //#endregion

  //#region model errors

  ERROR_MODEL_NO_EXIST_CODE: "5041",
  ERROR_MODEL_NO_EXIST_MESSAGE: "El {0} {1} no existe",

  ERROR_MODEL_CREATE_CODE: "5042",
  ERROR_MODEL_CREATE_MESSAGE: "Error al crear",

  ERROR_MODEL_UPDATE_CODE: "5043",
  ERROR_MODEL_UPDATE_MESSAGE: "Error al editar",

  ERROR_MODEL_DELETE_CODE: "5044",
  ERROR_MODEL_DELETE_MESSAGE: "Error al eliminar",
  
  ERROR_MODEL_ID_INVALID_CODE: "5045",
  ERROR_MODEL_ID_INVALID_MESSAGE: "Id invalido",

  //#endregion


};